In [55]:
import numpy as np



arr= np.array([[11,7,10,17,10],[13,21,7,11,13],[13,13,15,13,14],[18,10,13,16,14],[12,8,16,19,10]])
lengtharr=len(arr)

markedrow=[]
markedcol=[]
noassgnmarkedrow=[]

assign=np.zeros([lengtharr,lengtharr],dtype=np.int)
linelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
unlinelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
duallinelems=np.zeros([lengtharr,lengtharr],dtype=np.int)

assignflag=1

def step1(graph):
    for indx,row in enumerate(graph):
        rowmin=min(row)
        row=[elem-rowmin for elem in row]
        graph[indx]=row
    
    for indxi,row in enumerate(graph):
        for indxj,col in enumerate(row):
            if graph[indxi][indxj]==0 and (1 not in assign[indxi]) and (1 not in (assign.T)[indxj]) and assign[indxi][indxj]==0:
                assign[indxi][indxj]=1

        
def step2(graph):
    for indx,col in enumerate(graph.T):
        colmin=min(col)
        col=[elem-colmin for elem in col]
        graph.T[indx]=col
    for indxi,row in enumerate(graph):
        for indxj,col in enumerate(row):
            if graph[indxi][indxj]==0 and (1 not in assign[indxi]) and (1 not in (assign.T)[indxj]) and assign[indxi][indxj]==0:
                assign[indxi][indxj]=1

        

        
def step3(graph):
    global assignflag
    assignflag=0
    
    #ASSIGN STEP
    for indxi,row in enumerate(graph):
        for indxj,col in enumerate(row):
            if graph[indxi][indxj]==0 and (1 not in assign[indxi]) and (1 not in (assign.T)[indxj]):
                assign[indxi][indxj]=1
                print("I am here MF")
                assignflag+=1
    
    
    print("Assigning is done ",assign)
    
    global noassgnmarkedrow
    
    # MARKING ROW
    for indx,row in enumerate(assign):
        if not 1 in row:
            markedrow.append(indx)
            noassgnmarkedrow.append(indx)
    
    print("Marked rows are " ,markedrow)
    
    print("Graph is ",graph)
    
    # MARKING COLUMN
    for indx in noassgnmarkedrow:
        print("Came for row number", indx)
        row=graph[indx]
#         markedcol=[0]*lengtharr
        for indc,col in enumerate(row):
            if col==0 and indc not in markedcol:
                markedcol.append(indc)
                print("Column ",indc," has been marked")
        for colindx in markedcol:
            for indax,row in enumerate(graph):
                if assign[indax][colindx]==1 and indax not in markedrow:
                    print("Row ",indax," has been marked")
                    markedrow.append(indax)
        
    print("Marked columns are " ,markedcol)
    print("Marked rows are " ,markedrow)
    print("All markings are done")
    
#     linelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
#     unlinelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
#     duallinelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
    
    for rowinx,row in enumerate(graph):
        for colinx,col in enumerate(graph):
            if rowinx not in markedrow and colinx in markedcol:
                duallinelems[rowinx][colinx]=graph[rowinx][colinx]
                unlinelems[rowinx][colinx]=99999
                
            elif rowinx not in markedrow or colinx in markedcol:
                linelems[rowinx][colinx]=graph[rowinx][colinx]
                unlinelems[rowinx][colinx]=99999
                duallinelems[rowinx][colinx]=-99999
            else:
                unlinelems[rowinx][colinx]=graph[rowinx][colinx]
                duallinelems[rowinx][colinx]=-99999

    
    
    return graph
    
def step4(graph):
    print(graph)
    global linelems
    global unlinelems
    global duallinelems
    unlinemin=unlinelems.min()
    print("Unline elems are ",unlinelems)
    print("Dualelems arr",duallinelems)
    print("Line elems are ",linelems)
    
    
    print("Minimum is",unlinemin)
    
    
    unlinelems=unlinelems-unlinemin
    print("Unline elems are ",unlinelems)
    
    
#     duallinelems[duallinelems>0]=duallinelems+unlinemin   
    
    for i in range(len(duallinelems)):
        for j in range(len(duallinelems)):
            if duallinelems[i][j]>=0:
                duallinelems[i][j]+=unlinemin
    
    
    unlinelems[unlinelems>900]=0
    duallinelems[duallinelems<0]=0
    
    interm=np.add(duallinelems,unlinelems)
    
    
    graph=np.add(interm,linelems)
    
    return graph
    
    
step1(arr)
step2(arr)

print(arr)
assignflag=1

print("\n\n\nStep 3 started")

prevcount=0
while prevcount!=assignflag:
    
    
    assign=np.zeros([lengtharr,lengtharr],dtype=np.int)
    
    markedrow=[]
    markedcol=[]
    linelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
    unlinelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
    duallinelems=np.zeros([lengtharr,lengtharr],dtype=np.int)
    print("Assign flag is ",assignflag)
    prevcount=assignflag
    arr=step3(arr)
    arr=step4(arr)
    
    print(arr)
    print("==================================")


[[ 4  0  3 10  2]
 [ 6 14  0  4  5]
 [ 0  0  2  0  0]
 [ 8  0  3  6  3]
 [ 4  0  8 11  1]]



Step 3 started
Assign flag is  1
I am here MF
I am here MF
I am here MF
Assigning is done  [[0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Marked rows are  [3, 4]
Graph is  [[ 4  0  3 10  2]
 [ 6 14  0  4  5]
 [ 0  0  2  0  0]
 [ 8  0  3  6  3]
 [ 4  0  8 11  1]]
Came for row number 3
Column  1  has been marked
Row  0  has been marked
Came for row number 4
Marked columns are  [1]
Marked rows are  [3, 4, 0]
All markings are done
[[ 4  0  3 10  2]
 [ 6 14  0  4  5]
 [ 0  0  2  0  0]
 [ 8  0  3  6  3]
 [ 4  0  8 11  1]]
Unline elems are  [[    4 99999     3    10     2]
 [99999 99999 99999 99999 99999]
 [99999 99999 99999 99999 99999]
 [    8 99999     3     6     3]
 [    4 99999     8    11     1]]
Dualelems arr [[-99999 -99999 -99999 -99999 -99999]
 [-99999     14 -99999 -99999 -99999]
 [-99999      0 -99999 -99999 -99999]
 [-99999 -99999 -99999 -99999 -99999]
 [-99999 -99999

In [56]:
print(assign)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]]


In [58]:
assign=np.zeros([lengtharr,lengtharr],dtype=np.int)
for indxi,row in enumerate(arr):
    print(row)
    for indxj,col in enumerate(row):
        if arr[indxi][indxj]==0 and (1 not in assign[indxi]) and (1 not in (assign.T)[indxj]):
            assign[indxi][indxj]=1
            print("I am here MF")
            assignflag+=1


[0 0 0 6 1]
I am here MF
[ 5 17  0  3  7]
I am here MF
[0 4 3 0 3]
I am here MF
[4 0 0 2 2]
I am here MF
[0 0 5 7 0]
I am here MF


In [59]:
assign

array([[1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1]])