In [7]:
import numpy as np
class MaxFlow():
    def __init__(self,graph):
        self.graph=np.copy(graph)
        self.nodes=len(graph)
        self.orgraph=np.copy(graph)
        self.flow=np.zeros([self.nodes,self.nodes],np.int)
        self.mincut=[]
#         self.x=x    mURALI was here testing for x
        
    def BFS(self,source,target,parent):
        visited=[-1]*self.nodes
        
        que=[]
        que.append(source)
        visited[source]=1
        
        
        while que:
            
            psrc=que.pop(0)
            
            psrclist=self.graph[psrc]
            for vertex in range(self.nodes):
                if psrclist[vertex]>0 and visited[vertex]==-1:
                    que.append(vertex)
                    visited[vertex]=1
                    parent[vertex]=psrc
        return True if visited[target]==1 else False
    
    def DFS(self,source,target,visitedd):
        visitedd[source]=1
        for vrtx in range(self.nodes):
            if (self.graph[source][vrtx] and visitedd[vrtx]!=1):
                self.DFS(vrtx,target,visitedd)
            
        
    
    
    def ford_fulker(self,source,target):
        parent=[-1]*self.nodes
        flowi=0
        while self.BFS(source,target,parent):
            print(parent)
            path_min=999
            s=target

            while s!=source:
                path_min=min(path_min,self.graph[parent[s]][s])
                s=parent[s]



            v=target
            flowi+=path_min
            while v!=source:
                u=parent[v]
                print("path from ",u ," to ", v)
                self.flow[u,v]+=path_min   #Q1
                self.graph[u][v]-=path_min
                self.graph[v][u]+=path_min
                v=parent[v]
                
                
        ## ADJUST THE NEGATIVE EDGES HERE
        
        
        print(self.flow)
        for i in range(self.nodes):
            for j in range(self.nodes):
                if(self.flow[i][j]>0 and self.flow[j][i]>0 and (self.orgraph[i][j]==0 or self.orgraph[j][i]==0 )):
                    self.flow[i][j]=0
                    self.flow[j][i]=0
                    
                    
#         print("\n\n\n################ Question 1 ,Flows from all the edges #########")
        print(self.flow)
        
        
        
        ## MIN CUT
        
        

        for i in range(self.nodes):
            for j in range(self.nodes):
                if(self.graph[i][j]==0 and self.orgraph[i][j]):
#                     print( "Mincut is at ", i, " ",j," ",self.orgraph[i][j])
                    self.mincut=self.mincut+[tuple((i,j))]
        
        
        
        
        
        visitedd=[-1]*self.nodes
        self.DFS(source,target,visitedd)
        
        
#         x=input("Enter x")
#         x=int(x)
        
#         for i in range(self.nodes):
#             for j in range(self.nodes):
#                 if(visitedd[i]==1 and visitedd[j]!=1 and self.orgraph[i][j]):
#                     print( "Mincut is at ", i, " ",j," ",self.orgraph[i][j])
#                     if [tuple((i,j))] not in self.mincut:
#                         self.mincut=self.mincut+[tuple((i,j))]
                
                
    
        
        
        return flowi
            
        
        
            

In [8]:
# Create a graph given in the above diagram
 
# graph = [[0, 10, 20, 0],
#         [0, 0, 10, 10],
#         [0, 0, 0, 5],
#         [0, 0, 0, 0]]



# #@
# graph=[ [0, 9, 9, 0, 0, 0],
#         [0, 0, 4, 8, 0, 0],
#         [0, 0, 0, 1, 3, 0],
#         [0, 0, 0, 0, 8, 10],
#         [0, 0, 0, 0, 0, 7],
#         [0, 0, 0, 0, 0, 0]
#       ];



graph=[[0,3,2],[0,0,2],[0,0,0]]

#dammNN

source = 0; sink = 2
g = MaxFlow(graph)
x=int(input("Enter x"))
maxflow=g.ford_fulker(source, sink)
print ("The maximum possible flow is " ,maxflow )

print(g.mincut)


print("\n\n\n################ Question 1 ,Flows from all the edges #########")
print(g.flow)



print("\n\n\n################ Question 2 #########")
import itertools

subset=[]

for L in range(1, len(g.mincut)+1):
     for subst in itertools.combinations(g.mincut, L):
#         print(subst)
        lst=[ex for ex in subst]
        subset+=[lst]
        

for sub in subset:
    graph2=np.copy(graph)
    
    print("\n\n\n Checking subset",sub,"\n\n\n")
    for i,j in sub:
        graph2[i][j]=graph2[i][j]+x
    g2 = MaxFlow(graph2)
    print(source,sink)
    currmaxflow=g2.ford_fulker(source, sink)
    if currmaxflow==maxflow+x:
        print ("The maximum possible flow is " , currmaxflow)
            
        print("\n\n\n")
        print("Present for ",sub)    
        print("\n\n\n")
        break

       
        
        
        
#         graph2[i][j]=graph2[i][j]+g.x
#         g2 = MaxFlow(graph2)
#         source = 0; sink = 3
#         print ("The maximum possible flow is " , g2.ford_fulker(source, sink))

# print(g.x)

# for i,j in g.mincutarr:
#     graph2[i][j]=graph2[i][j]+g.x

# print(graph2)
    
# g2 = MaxFlow(graph2)
# source = 0; sink = 3
  
# print ("The maximum possible flow is " , g2.ford_fulker(source, sink))



Enter x34
[-1, 0, 0]
path from  0  to  2
[-1, 0, 1]
path from  1  to  2
path from  0  to  1
[[0 2 2]
 [0 0 2]
 [0 0 0]]
[[0 2 2]
 [0 0 2]
 [0 0 0]]
The maximum possible flow is  4
[(0, 2), (1, 2)]



################ Question 1 ,Flows from all the edges #########
[[0 2 2]
 [0 0 2]
 [0 0 0]]



################ Question 2 #########



 Checking subset [(0, 2)] 



0 2
[-1, 0, 0]
path from  0  to  2
[-1, 0, 1]
path from  1  to  2
path from  0  to  1
[[ 0  2 36]
 [ 0  0  2]
 [ 0  0  0]]
[[ 0  2 36]
 [ 0  0  2]
 [ 0  0  0]]
The maximum possible flow is  38




Present for  [(0, 2)]




