In [56]:

import numpy as np
class Graph2:
    def __init__(self,graph):
        self.originalgraph=np.copy(graph)
        self.rgraph=np.copy(graph)
        self.nodes=len(graph)
        self.height=[0]*self.nodes
        self.xcsflow=[0]*self.nodes
#         self.flow=[0]*self.nodes
        self.flow=np.zeros([self.nodes,self.nodes],dtype=np.int)
        self.pathfound=False
        self.totalflow=0
        self.path=[]
        
        
        
    def initialize(self,source,sink):
        
        ## SETTING HEIGHTS
        self.height[source]=self.nodes
        self.height[sink]=0
        
        ## SETTING FLOWS
#         self.flow=[0]*self.nodes
        self.flow=np.zeros([self.nodes,self.nodes],dtype=np.int)

#         ## setting flows of every edge as ZERO
#         self.edgeflow=np.zeros([self.nodes,self.nodes],dtype=np.int)
        
        ## setting flow and xcsflow of source adj nodes:
        for u in range(self.nodes):
            if self.rgraph[source][u]>0:
#                 self.flow[u]=self.rgraph[source][u]
#                 self.inflow[u]=self.rgraph[source][u]
                self.xcsflow[u]=self.rgraph[source][u]
                self.flow[source][u]=self.rgraph[source][u]
                self.rgraph[u][source]=self.rgraph[source][u]
                self.rgraph[source][u]=0
        
        
        
    def check_nodes_with_excess_flow(self):
        print(self.xcsflow)
        for i in range(self.nodes):
            if self.xcsflow[i]>0:
#                 print(" Excess FLOW AT ",i)
                return i
            
        return -1
    
    def push(self,v):
        flag=False
        for w in range(self.nodes) :
            if self.rgraph[v][w]>0 and self.height[v]>self.height[w]:
                
                
                if self.originalgraph[v][w]>0:
            
                    edgepath=self.originalgraph[v][w]-self.flow[v][w]
                    minpath=min(edgepath,self.xcsflow[v])
                    self.flow[v][w]+=minpath
#                     print("Minimum of ",edgepath," ",self.xcsflow[v])
                    
                else:                  ## if   edge(v,w) is a backward edge
                    
                    edgepath=self.flow[w][v]
                    minpath=min(edgepath,self.xcsflow[v])
                    self.flow[w][v]-=minpath
                
#                 print("Minpath is ")
                print("Path from ",v, " to ",w," has minpath of ",minpath)
                self.xcsflow[v]=self.xcsflow[v]-minpath
                self.rgraph[v][w]=self.rgraph[v][w]-minpath
                self.rgraph[w][v]=self.rgraph[w][v]+minpath
                
                if w==source:
                    pass
                elif w==sink:
#                     self.pathfound=True
                    self.totalflow+=minpath
#                     print ("path found")
#                     print("================================================")
                else:
                    self.xcsflow[w]+=minpath
                
                self.path.append(v)
                self.path.append(w)
                
                flag=True
                break
            
        return flag
            
        
    def relabel(self,v):
#         print("Called relabel")
        flag=False
        found=False
        
        foundposedge=False
        
        for w in range(self.nodes) :
            if w==0:
                print(self.rgraph[v][w],self.height[v],self.height[w])
            if self.rgraph[v][w]>0:
                foundposedge=True
            if self.rgraph[v][w]>0 and self.height[v]>self.height[w]:
                found=True
                break
            
            
            
            
        if found==False and foundposedge==True:
            self.height[v]=self.height[v]+1
            print("Incremented height of the vertex ",v ," from ",self.height[v]-1 , " to ",self.height[v] )
            flag=True
            
        return flag
        
    
    
    
    def push_relabel(self,source,sink):
        self.initialize(source,sink)
        
        while(self.check_nodes_with_excess_flow()!=-1):
            v=self.check_nodes_with_excess_flow()
            if not self.push(v):
                self.relabel(v)
        
            
    def return_path(self,source,sink):
        flowcopy=np.copy(self.flow)
        paths=[]
        for indx in range(self.nodes):
#             print("")
            if flowcopy[indx][sink]>0:
                path=[]
#                 print("Path",end="===>")
                pointr=indx
#                 print(sink,indx,end=" ")
                path.append(sink)
                path.append(indx)
                path_min=flowcopy[indx][sink]
                
                while pointr != source:
                    
                    for inx in range(self.nodes):
                        if flowcopy[inx][pointr]>0:
                            flowcopy[inx][pointr]-=path_min
                            pointr=inx
#                             print(pointr,end=" ")
                            path.append(pointr)
                            break
                paths.append(path)
        print(paths)
        return paths

In [64]:
# graph=[
#     [0,5,3,0],
#     [0,0,2,1],
#     [0,0,0,2],
#     [0,0,0,0]
#     ]

# graph = [[0, 10, 20, 0],
#         [0, 0, 15, 10],
#         [0, 0, 0, 5],
#         [0, 0, 0, 0]]

# graph=[ [0, 9, 9, 0, 0, 0],
#         [0, 0, 4, 8, 0, 0],
#         [0, 0, 0, 1, 3, 0],
#         [0, 0, 0, 0, 0, 10],
#         [0, 0, 0, 0, 8, 7],
#         [0, 0, 0, 0, 0, 0]
#       ];
graph=[[0,3,2],[0,0,2],[0,0,0]]

g=Graph2(graph)
source=0
sink=2
g.push_relabel(source,sink)
print(g.rgraph)
print(g.flow)
print(g.return_path(source,sink))

[0, 3, 2]
[0, 3, 2]
3 0 3
Incremented height of the vertex  1  from  0  to  1
[0, 3, 2]
[0, 3, 2]
Path from  1  to  2  has minpath of  2
[0, 1, 2]
[0, 1, 2]
3 1 3
Incremented height of the vertex  1  from  1  to  2
[0, 1, 2]
[0, 1, 2]
3 2 3
Incremented height of the vertex  1  from  2  to  3
[0, 1, 2]
[0, 1, 2]
3 3 3
Incremented height of the vertex  1  from  3  to  4
[0, 1, 2]
[0, 1, 2]
Path from  1  to  0  has minpath of  1
[0, 0, 2]
[0, 0, 2]
2 0 3
Incremented height of the vertex  2  from  0  to  1
[0, 0, 2]
[0, 0, 2]
2 1 3
Incremented height of the vertex  2  from  1  to  2
[0, 0, 2]
[0, 0, 2]
2 2 3
Incremented height of the vertex  2  from  2  to  3
[0, 0, 2]
[0, 0, 2]
2 3 3
Incremented height of the vertex  2  from  3  to  4
[0, 0, 2]
[0, 0, 2]
Path from  2  to  0  has minpath of  2
[0, 0, 0]
[[0 1 2]
 [2 0 0]
 [0 2 0]]
[[0 2 0]
 [0 0 2]
 [0 0 0]]
[[2, 1, 0]]
[[2, 1, 0]]


In [60]:
print(g.totalflow)

12


In [61]:
print(g.height)

[6, 7, 7, 1, 1, 0]


In [63]:
print(g.return_path(source,sink))

[[5, 3, 1, 0], [5, 4, 2, 0]]
[[5, 3, 1, 0], [5, 4, 2, 0]]
